//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IWorkflowService")]
public interface IWorkflowService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWorkflowService/InvokeWorkflow", ReplyAction = "http://tempuri.org/IWorkflowService/InvokeWorkflowResponse")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Diagnostics.EventLogEntry[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Diagnostics.EventLogEntry))]
    object InvokeWorkflow(string workflowData);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWorkflowService/InvokeWorkflow", ReplyAction = "http://tempuri.org/IWorkflowService/InvokeWorkflowResponse")]
    System.Threading.Tasks.Task<object> InvokeWorkflowAsync(string workflowData);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWorkflowService/InvokeEventsWorkflow", ReplyAction = "http://tempuri.org/IWorkflowService/InvokeEventsWorkflowResponse")]
    System.Diagnostics.EventLogEntry[] InvokeEventsWorkflow(string workflowData);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWorkflowService/InvokeEventsWorkflow", ReplyAction = "http://tempuri.org/IWorkflowService/InvokeEventsWorkflowResponse")]
    System.Threading.Tasks.Task<System.Diagnostics.EventLogEntry[]> InvokeEventsWorkflowAsync(string workflowData);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IWorkflowServiceChannel : IWorkflowService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WorkflowServiceClient : System.ServiceModel.ClientBase<IWorkflowService>, IWorkflowService
{

    public WorkflowServiceClient()
    {
    }

    public WorkflowServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public WorkflowServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public WorkflowServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public WorkflowServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public object InvokeWorkflow(string workflowData)
    {
        return base.Channel.InvokeWorkflow(workflowData);
    }

    public System.Threading.Tasks.Task<object> InvokeWorkflowAsync(string workflowData)
    {
        return base.Channel.InvokeWorkflowAsync(workflowData);
    }

    public System.Diagnostics.EventLogEntry[] InvokeEventsWorkflow(string workflowData)
    {
        return base.Channel.InvokeEventsWorkflow(workflowData);
    }

    public System.Threading.Tasks.Task<System.Diagnostics.EventLogEntry[]> InvokeEventsWorkflowAsync(string workflowData)
    {
        return base.Channel.InvokeEventsWorkflowAsync(workflowData);
    }
}